### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.main.MainActivity}: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by hyb1996-guest** [hyb1996/NoRootScriptDroid#132]
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.main.MainActivity}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3423)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3463)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1525)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6114)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:1687)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5497)
	at android.app.Activity.isTopOfTask(Activity.java:6025)
	at android.app.Activity.onResume(Activity.java:1269)
	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
	at android.app.Activity.performResume(Activity.java:6849)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
	... 8 more

-

Device info:
---
<table>
<tr><td>App version</td><td>2.0.2 Beta</td></tr>
<tr><td>App version code</td><td>104</td></tr>
<tr><td>Android build version</td><td>V8.2.1.0.NAACNEB</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>gemini</td></tr>
<tr><td>Device model</td><td>MI 5</td></tr>
<tr><td>Device product name</td><td>gemini</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheLester** [comment]
What was the reason of this crash?

**Comment by hyb1996** [comment]
Maybe issue #133 could help you.
