### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.main.MainActivity}: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by hyb1996-guest** [hyb1996/NoRootScriptDroid#133]
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.main.MainActivity}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3429)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:1688)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5505)
	at android.app.Activity.isTopOfTask(Activity.java:5981)
	at android.app.Activity.onResume(Activity.java:1252)
	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
	at android.app.Activity.performResume(Activity.java:6786)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
	... 8 more

-

Device info:
---
<table>
<tr><td>App version</td><td>2.0.5 Beta</td></tr>
<tr><td>App version code</td><td>108</td></tr>
<tr><td>Android build version</td><td>3635581</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NPG05D</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>bullhead</td></tr>
<tr><td>Device model</td><td>Nexus 5X</td></tr>
<tr><td>Device product name</td><td>bullhead</td></tr>
<tr><td>Device hardware name</td><td>bullhead</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by CatInt** [comment]
I have encountered this problem...
I'm wondering if this issue has been located or ?

**Comment by hyb1996** [comment]
This issue have been fixed long ago.
Are you using the latest version?

**Comment by CatInt** [comment]
Aha...I have encountered this issue on my application.
Would u like to claim the fixing detail?

**Comment by hyb1996** [comment]
I used a field to store a fragment instance, likes `private MyFragment mFragment = new MyFragment();`. But a fragment may be destroyed and become invalid after activity pauses. That caused the problem. 
A solution is using FragmentManager.findFragmentBy** to get a fragment instance when you need it.

**Comment by CatInt** [comment]
Appreciate your reply.
I am going to review my code for search if there is any usage of probably-destroyed fragment.

**Comment by hendrawd** [comment]
Maybe because of https://issuetracker.google.com/issues/66849632
