### ISSUE TITLE
开启通知监听的函数无法使用，只要监听到通知就立即崩溃

### ISSUE THREAD

**Issue by tanyichao** [hyb1996/NoRootScriptDroid#232]
版本Auto.js 2.0.16 Beta2.1
开启通知监听的函数无法使用，只要监听到通知就立即崩溃，没有成功产生日志
崩溃后手机按键失效，屏幕能正常点击。重启手机后正常。
Version: 163
Android: 19
java.lang.NullPointerException
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
	at java.lang.StringBuilder.<init>(StringBuilder.java:95)
	at com.stardust.autojs.ScriptEngineService.getScriptTrace(ScriptEngineService.java:251)
	at com.stardust.autojs.ScriptEngineService.access$100(ScriptEngineService.java:40)
	at com.stardust.autojs.ScriptEngineService$1.onException(ScriptEngineService.java:72)
	at com.stardust.autojs.execution.ScriptExecutionObserver.onException(ScriptExecutionObserver.java:29)
	at com.stardust.autojs.execution.ScriptExecutionObserver$Wrapper.onException(ScriptExecutionObserver.java:66)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:41)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:32)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:27)
	at java.lang.Thread.run(Thread.java:841)
	at com.stardust.lang.ThreadCompat.run(ThreadCompat.java:61)

**Comment by tanyichao** [comment]
群里发的3.0版本这个问题还没有解决
