### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.edit.EditActivity}: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by hyb1996-guest** [hyb1996/NoRootScriptDroid#87]
java.lang.RuntimeException: Unable to resume activity {com.stardust.scriptdroid/com.stardust.scriptdroid.ui.edit.EditActivity}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3444)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3484)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:1688)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5535)
	at android.app.Activity.isTopOfTask(Activity.java:5978)
	at android.app.Activity.onResume(Activity.java:1252)
	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
	at android.app.Activity.performResume(Activity.java:6783)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3421)
	... 8 more

-

Device info:
---
<table>
<tr><td>App version</td><td>2.0.5 Beta</td></tr>
<tr><td>App version code</td><td>108</td></tr>
<tr><td>Android build version</td><td>e8c448d52a</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>mk_libra-userdebug 7.1.1 NOF26W e8c448d52a test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>libra</td></tr>
<tr><td>Device model</td><td>Mi-4c</td></tr>
<tr><td>Device product name</td><td>mk_libra</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by vijaybharatigate6** [comment]
Unable to resume activity {com..example.demo/com.example.demo.activity.MainActivity}: java.lang.IllegalArgumentException
