### ISSUE TITLE
java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary

### ISSUE THREAD

**Issue by hyb1996-guest** [hyb1996/NoRootScriptDroid#93]
java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
	at com.jecelyin.editor.v2.core.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:703)
	at com.jecelyin.editor.v2.core.text.SpannableStringBuilder.change(SpannableStringBuilder.java:444)
	at com.jecelyin.editor.v2.core.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:580)
	at com.jecelyin.editor.v2.core.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:510)
	at com.jecelyin.editor.v2.core.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:57)
	at com.jecelyin.editor.v2.core.widget.TextView.paste(TextView.java:8893)
	at com.jecelyin.editor.v2.core.widget.TextView.onTextContextMenuItem(TextView.java:8708)
	at com.jecelyin.editor.v2.core.widget.EditableInputConnection.performContextMenuAction(EditableInputConnection.java:154)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:381)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

-

Device info:
---
<table>
<tr><td>App version</td><td>2.0.5 Beta</td></tr>
<tr><td>App version code</td><td>108</td></tr>
<tr><td>Android build version</td><td>e8c448d52a</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>mk_libra-userdebug 7.1.1 NOF26W e8c448d52a test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>libra</td></tr>
<tr><td>Device model</td><td>Mi-4c</td></tr>
<tr><td>Device product name</td><td>mk_libra</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Larnoo** [comment]
这个bug修复了嘛 @hyb1996

**Comment by hyb1996** [comment]
这个bug是用的920编辑器的bug，现在已经更换编辑了
